FROM debian:9

ARG JENKINS_GROUP_ID=200
ARG JENKINS_USER_ID=200

RUN groupadd --gid $JENKINS_GROUP_ID jenkins && \
    useradd --uid $JENKINS_USER_ID --gid $JENKINS_GROUP_ID --create-home jenkins

RUN apt-get update && \
    apt-get install -y git openjdk-8-jdk=8u171-b11-1~deb9u1 openjdk-8-jdk-headless=8u171-b11-1~deb9u1 openjdk-8-jre=8u171-b11-1~deb9u1 openjdk-8-jre-headless=8u171-b11-1~deb9u1 maven

COPY docker/entrypoint-java.sh /entrypoint-java.sh

ENTRYPOINT [ "/entrypoint-java.sh" ]
